// constants/iconMap.ts
export const iconMap: Record<string, any> = {
  "tea.png": require("../assets/images/tea.png"),
  "biscuit.png": require("../assets/images/biscuit.png"),
  "cigarette.png": require("../assets/images/cigarette.png"),
  "burger.png": require("../assets/images/burger.png"),
  "rupee.png": require("../assets/images/rupee.png"),
  "rupee-circle.png": require("../assets/images/rupee-circle.png"),
  "add-customer.png": require("../assets/images/add-customer.png"),
  "bell.png": require("../assets/images/bell.png"),
  "reminder-bell.png": require("../assets/images/reminder-bell.png"),
  "menu.png": require("../assets/images/menu.png"),
  "arrow-right.png": require("../assets/images/arrow-right.png"),
  "link.png": require("../assets/images/link.png"),
  "delete.png": require("../assets/images/delete.png"),
  "clock.png": require("../assets/images/clock.png"),
  "check.png": require("../assets/images/check.png"),
  "shop.png": require("../assets/images/shop.png"),
  "user.png": require("../assets/images/user.png"),
  "wallet.png": require("../assets/images/wallet.png"),
};
