/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/roleSelection` | `/roleSelection`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customerTabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customerTabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customerTabs)'}/shops` | `/shops`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ownerTabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ownerTabs)'}/products` | `/products`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ownerTabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/roleSelection` | `/roleSelection`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customerTabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customerTabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customerTabs)'}/shops` | `/shops`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(ownerTabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(ownerTabs)'}/products` | `/products`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(ownerTabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/roleSelection${`?${string}` | `#${string}` | ''}` | `/roleSelection${`?${string}` | `#${string}` | ''}` | `${'/(customerTabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(customerTabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(customerTabs)'}/shops${`?${string}` | `#${string}` | ''}` | `/shops${`?${string}` | `#${string}` | ''}` | `${'/(ownerTabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(ownerTabs)'}/products${`?${string}` | `#${string}` | ''}` | `/products${`?${string}` | `#${string}` | ''}` | `${'/(ownerTabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/roleSelection` | `/roleSelection`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customerTabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customerTabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customerTabs)'}/shops` | `/shops`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ownerTabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ownerTabs)'}/products` | `/products`; params?: Router.UnknownInputParams; } | { pathname: `${'/(ownerTabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
